#!/bin/bash

echo "================================================
📋 Odoo Module Selector for Production
================================================
This tool helps you create a custom module list
for your production Odoo installation.
================================================
"

# Configuration
SCRIPT_DIR="$(dirname "$0")"
OUTPUT_FILE="$SCRIPT_DIR/../config/modules_production.txt"
TEMP_FILE="$SCRIPT_DIR/../config/.modules_temp.txt"

# Initialize temp file with header
cat > "$TEMP_FILE" << 'EOF'
# Production Modules List
# Generated by module_selector.sh
# Date: $(date)

# === CORE MODULES (Always Included) ===
base
web
mail
calendar
contacts

EOF

echo "Select the module categories you need:"
echo ""

# Sales & CRM
echo -n "1. Sales & CRM modules? (y/N): "
read -r INSTALL_SALES
if [[ "$INSTALL_SALES" =~ ^[Yy]$ ]]; then
    cat >> "$TEMP_FILE" << 'EOF'
# === SALES & CRM ===
sale_management
sale
crm
sale_stock
sale_purchase

EOF
fi

# Inventory & Manufacturing
echo -n "2. Inventory & Manufacturing? (y/N): "
read -r INSTALL_INVENTORY
if [[ "$INSTALL_INVENTORY" =~ ^[Yy]$ ]]; then
    cat >> "$TEMP_FILE" << 'EOF'
# === INVENTORY & MANUFACTURING ===
stock
purchase
mrp

EOF
fi

# Accounting
echo -n "3. Accounting modules? (y/N): "
read -r INSTALL_ACCOUNTING
if [[ "$INSTALL_ACCOUNTING" =~ ^[Yy]$ ]]; then
    cat >> "$TEMP_FILE" << 'EOF'
# === ACCOUNTING ===
account
account_payment

EOF
fi

# Human Resources
echo -n "4. Human Resources modules? (y/N): "
read -r INSTALL_HR
if [[ "$INSTALL_HR" =~ ^[Yy]$ ]]; then
    cat >> "$TEMP_FILE" << 'EOF'
# === HUMAN RESOURCES ===
hr
hr_holidays
hr_recruitment
hr_expense
hr_attendance

EOF
fi

# Project Management
echo -n "5. Project Management? (y/N): "
read -r INSTALL_PROJECT
if [[ "$INSTALL_PROJECT" =~ ^[Yy]$ ]]; then
    cat >> "$TEMP_FILE" << 'EOF'
# === PROJECT MANAGEMENT ===
project
project_todo

EOF
fi

# Website & eCommerce
echo -n "6. Website & eCommerce? (y/N): "
read -r INSTALL_WEBSITE
if [[ "$INSTALL_WEBSITE" =~ ^[Yy]$ ]]; then
    cat >> "$TEMP_FILE" << 'EOF'
# === WEBSITE & ECOMMERCE ===
website
website_sale
website_blog
website_event

EOF
fi

# Marketing
echo -n "7. Marketing tools? (y/N): "
read -r INSTALL_MARKETING
if [[ "$INSTALL_MARKETING" =~ ^[Yy]$ ]]; then
    cat >> "$TEMP_FILE" << 'EOF'
# === MARKETING ===
mass_mailing
mass_mailing_sms
marketing_automation

EOF
fi

# Helpdesk
echo -n "8. Helpdesk & Support? (y/N): "
read -r INSTALL_HELPDESK
if [[ "$INSTALL_HELPDESK" =~ ^[Yy]$ ]]; then
    cat >> "$TEMP_FILE" << 'EOF'
# === HELPDESK & SUPPORT ===
helpdesk
website_helpdesk

EOF
fi

# Other Tools
echo -n "9. Other tools (Survey, Documents, IoT)? (y/N): "
read -r INSTALL_OTHER
if [[ "$INSTALL_OTHER" =~ ^[Yy]$ ]]; then
    cat >> "$TEMP_FILE" << 'EOF'
# === OTHER TOOLS ===
survey
documents
sign
board

EOF
fi

# Process the date in temp file
sed -i.bak "s/\$(date)/$(date)/" "$TEMP_FILE" && rm "$TEMP_FILE.bak"

# Show summary
echo ""
echo "================================================"
echo "📊 Module Selection Summary"
echo "================================================"
echo "Modules to be installed:"
grep -v "^#" "$TEMP_FILE" | grep -v "^$" | sort | uniq | nl
TOTAL_MODULES=$(grep -v "^#" "$TEMP_FILE" | grep -v "^$" | sort | uniq | wc -l)
echo ""
echo "Total modules selected: $TOTAL_MODULES"
echo "================================================"

# Confirm and save
echo ""
echo -n "Save this configuration? (y/N): "
read -r SAVE_CONFIG

if [[ "$SAVE_CONFIG" =~ ^[Yy]$ ]]; then
    mv "$TEMP_FILE" "$OUTPUT_FILE"
    echo "✅ Configuration saved to: config/modules_production.txt"
    echo ""
    echo "You can now run the automated setup with your custom module list!"
else
    rm "$TEMP_FILE"
    echo "❌ Configuration discarded."
fi

echo ""
echo "================================================"